config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/dashboard'
  
    get 'pages/login'
  
    get 'pages/logout'
  
    get 'pages/contact'
  
    get 'pages/about'
    
    get 'pages/register'
    get 'pages/contact'
    get 'orders/order'

    post 'pages/login_attempt'
  resources :product_categories
  resources :orders
  resources :carts
  resources :customer_details
  resources :customers
  resources :products
  resources :offers
  resources :units
  resources :backend_users
  resources :roles
  
  
root "pages#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backend_user.rb
class BackendUser < ApplicationRecord
  belongs_to :role
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
end

app/models/customer_detail.rb
class CustomerDetail < ApplicationRecord
  belongs_to :customer
end

app/models/offer.rb
class Offer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :product_image1, ProductUploader
  belongs_to :product_category
  
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :unit
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:product_id, :customer_id, :quantity, :total_amount, :is_checked_out)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    if params[:id].present?
      @products = Product.where(product_category_id: params[:id].to_i)
    else
    @products = Product.all
    end
  end

  def login
  end

  def contact
  end

  def about
  end

  def register
  end
  def contact
  end

  def login_attempt
    username = params[:username_or_email]
    password = params[:password]
    @user = Customer.find_by(email_id: username) if username.include? "@"
    @user = Customer.find_by(first_name: username) unless username.include? "@"
    if password == @user.password
      session[:user_id]= @user.id
      redirect_to pages_dashboard_path
    else
      redirect_to pages_login_path
    end
  end


  def product_view

  end

  
  def logout
    session[:user_id]=nil
    redirect_to pages_dashboard_path
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:role, :role_name, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :cart_product_id %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id, id: :cart_customer_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :cart_quantity %>
  </div>

  <div class="field">
    <%= form.label :total_amount %>
    <%= form.text_field :total_amount, id: :cart_total_amount %>
  </div>

  <div class="field">
    <%= form.label :is_checked_out %>
    <%= form.check_box :is_checked_out, id: :cart_is_checked_out %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Customer</th>
      <th>Quantity</th>
      <th>Total amount</th>
      <th>Is checked out</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.product %></td>
        <td><%= cart.customer %></td>
        <td><%= cart.quantity %></td>
        <td><%= cart.total_amount %></td>
        <td><%= cart.is_checked_out %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @cart.product %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @cart.customer %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cart.quantity %>
</p>

<p>
  <strong>Total amount:</strong>
  <%= @cart.total_amount %>
</p>

<p>
  <strong>Is checked out:</strong>
  <%= @cart.is_checked_out %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role, id: :role_role %>
  </div>

  <div class="field">
    <%= form.label :role_name %>
    <%= form.text_field :role_name, id: :role_role_name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc, id: :role_desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Role</th>
      <th>Role name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.role %></td>
        <td><%= role.role_name %></td>
        <td><%= role.desc %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role:</strong>
  <%= @role.role %>
</p>

<p>
  <strong>Role name:</strong>
  <%= @role.role_name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @role.desc %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>