config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/dashboard'
  
    get 'pages/login'
  
    get 'pages/logout'
  
    get 'pages/contact'
  
    get 'pages/about'
    
    get 'pages/register'
    get 'pages/contact'
    get 'orders/order'

    post 'pages/login_attempt'
  resources :product_categories
  resources :orders
  resources :carts
  resources :customer_details
  resources :customers
  resources :products
  resources :offers
  resources :units
  resources :backend_users
  resources :roles
  
  
root "pages#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backend_user.rb
class BackendUser < ApplicationRecord
  belongs_to :role
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
end

app/models/customer_detail.rb
class CustomerDetail < ApplicationRecord
  belongs_to :customer
end

app/models/offer.rb
class Offer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :product_image1, ProductUploader
  belongs_to :product_category
  
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :unit
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:product_id, :customer_id, :quantity, :total_amount, :is_checked_out)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    if params[:id].present?
      @products = Product.where(product_category_id: params[:id].to_i)
    else
    @products = Product.all
    end
  end

  def login
  end

  def contact
  end

  def about
  end

  def register
  end
  def contact
  end

  def login_attempt
    username = params[:username_or_email]
    password = params[:password]
    @user = Customer.find_by(email_id: username) if username.include? "@"
    @user = Customer.find_by(first_name: username) unless username.include? "@"
    if password == @user.password
      session[:user_id]= @user.id
      redirect_to pages_dashboard_path
    else
      redirect_to pages_login_path
    end
  end


  def product_view

  end

  
  def logout
    session[:user_id]=nil
    redirect_to pages_dashboard_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :quantity, :min_quantity, :price, :discount, :subscription_date, :min_delivery_date, :product_category_id, :product_image1)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name, id: :product_product_name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :product_quantity %>
  </div>

  <div class="field">
    <%= form.label :min_quantity %>
    <%= form.text_field :min_quantity, id: :product_min_quantity %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount, id: :product_discount %>
  </div>

  <div class="field">
    <%= form.label :subscription_date %>
    <%= form.text_field :subscription_date, id: :product_subscription_date %>
  </div>

  <div class="field">
    <%= form.label :min_delivery_date %>
    <%= form.text_field :min_delivery_date, id: :product_min_delivery_date %>
  </div>

  <div class="field">
    <%= form.label :product_category_id %>
    <%= form.text_field :product_category_id, id: :product_product_category_id %>
  </div>
  <div class="field">
    <%= form.label :product_category_id %>
    <%= form.file_field :product_image1, id: :product_image1_id %>
  </div>
  <div class="field">
    <%= form.label :product_category_id %>
    <%= form.text_field :product_image2, id: :product_image2_id %>
  </div>
  <div class="field">
    <%= form.label :product_category_id %>
    <%= form.text_field :product_image3, id: :product_product_category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Quantity</th>
      <th>Min quantity</th>
      <th>Price</th>
      <th>Discount</th>
      <th>Subscription date</th>
      <th>Min delivery date</th>
      <th>Product category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.quantity %></td>
        <td><%= product.min_quantity %></td>
        <td><%= product.price %></td>
        <td><%= product.discount %></td>
        <td><%= product.subscription_date %></td>
        <td><%= product.min_delivery_date %></td>
        <td><%= product.product_category %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<!--p id="notice"><%#= notice %></p>

<p>
  <strong>Product name:</strong>
  <%#= @product.product_name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%#= @product.quantity %>
</p>

<p>
  <strong>Min quantity:</strong>
  <%#= @product.min_quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%#= @product.price %>
</p>

<p>
  <strong>Discount:</strong>
  <%#= @product.discount %>
</p>

<p>
  <strong>Subscription date:</strong>
  <%#= @product.subscription_date %>
</p>

<p>
  <strong>Min delivery date:</strong>
  <%#= @product.min_delivery_date %>
</p>

<p>
  <strong>Product category:</strong>
  <%#= @product.product_category %>
</p>

<%#= link_to 'Edit', edit_product_path(@product) %> |
<%#= link_to 'Back', products_path %>
-->

<div class="single">
			<div class="container">
						<div class="single-top-main">
	   		<div class="col-md-5 single-top">
	   		<div class="single-w3agile">
							
<div id="picture-frame">
<%unless @product.product_image1.nil?%>
<%=image_tag @product.product_image1, class: "img-responsive"%>
<%else%>
<%=image_tag 'no_img.png', class: "img-responsive"%>
<%end%>
			<%# <img src="images/si.jpg" data-src="images/si-1.jpg" alt="" class="img-responsive"/> %>
		</div>
										<script src="js/jquery.zoomtoo.js"></script>
								<script>
			$(function() {
				$("#picture-frame").zoomToo({
					magnify: 1
				});
			});
		</script>
		
		
			</div>
			</div>
			<div class="col-md-7 single-top-left ">
								<div class="single-right">
				<h3><%= @product.product_name%></h3>
				
					
				 <div class="pr-single">
				  <p class="reduced "><del><%= @product.price%>Rs</del><%= @product.price.to_i - 100/(@product.discount.to_i)%> Rs</p>
				</div>
				<div class="block block-w3">
					<div class="starbox small ghosting"> </div>
				</div>
				<p class="in-pa"> There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>
			   	
				<ul class="social-top">
					<li><a href="#" class="icon facebook"><i class="fa fa-facebook" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon twitter"><i class="fa fa-twitter" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon pinterest"><i class="fa fa-pinterest-p" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i><span></span></a></li>
				</ul>
					<div class="add add-3">
										
										   <%= link_to "Buy now", orders_order_path(product: @product), class: "btn btn-danger my-cart-btn my-cart-b "%>
										</div>
				
			   
			<div class="clearfix"> </div>
			</div>
		 

			</div>
		   <div class="clearfix"> </div>
	   </div>	
				 
				
	</div>
</div>