config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/dashboard'
  
    get 'pages/login'
  
    get 'pages/logout'
  
    get 'pages/contact'
  
    get 'pages/about'
    
    get 'pages/register'
    get 'pages/contact'
    get 'orders/order'

    post 'pages/login_attempt'
  resources :product_categories
  resources :orders
  resources :carts
  resources :customer_details
  resources :customers
  resources :products
  resources :offers
  resources :units
  resources :backend_users
  resources :roles
  
  
root "pages#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backend_user.rb
class BackendUser < ApplicationRecord
  belongs_to :role
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
end

app/models/customer_detail.rb
class CustomerDetail < ApplicationRecord
  belongs_to :customer
end

app/models/offer.rb
class Offer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :product_image1, ProductUploader
  belongs_to :product_category
  
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :unit
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
    <div class="col-md-3 footer-grid">
        <h3>About Us</h3>
        <p>Nam libero tempore, cum soluta nobis est eligendi 
            optio cumque nihil impedit quo minus id quod maxime 
            placeat facere possimus.</p>
    </div>
    <div class="col-md-3 footer-grid ">
        <h3>Menu</h3>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="kitchen.html">Kitchen</a></li>
            <li><a href="care.html">Personal Care</a></li>
            <li><a href="hold.html">Household</a></li>						 
            <li><a href="codes.html">Short Codes</a></li> 
            <li><a href="contact.html">Contact</a></li>
        </ul>
    </div>
    <div class="col-md-3 footer-grid ">
        <h3>Customer Services</h3>
        <ul>
            <li><a href="shipping.html">Shipping</a></li>
            <li><a href="terms.html">Terms & Conditions</a></li>
            <li><a href="faqs.html">Faqs</a></li>
            <li><a href="contact.html">Contact</a></li>
            <li><a href="offer.html">Online Shopping</a></li>						 
             
        </ul>
    </div>
    <div class="col-md-3 footer-grid">
        <h3>My Account</h3>
        <ul>
        <%unless current_user.present?%>
            <li><a href="<%= pages_login_path%>">Login</a></li>
            <li><a href="<%=pages_register_path%>">Register</a></li>
            <%else%>
            <li><a href="<%=pages_logout_path%>">Logout</a></li>
            <%end%>            
            <li><a href="wishlist.html">Wishlist</a></li>
            
        </ul>
    </div>
    <div class="clearfix"></div>
        <div class="footer-bottom">
            <h2 ><a href="index.html"><b>K<br>T<br>I</b>&nbsp Kurinjithinai<span>The Food From God</span></a></h2>
            <p class="fo-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>
            <ul class="social-fo">
                <li><a href="#" class=" face"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#" class=" twi"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="#" class=" pin"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                <li><a href="#" class=" dri"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
            </ul>
            <div class=" address">
                <div class="col-md-4 fo-grid1">
                        <p><i class="fa fa-home" aria-hidden="true"></i>12 th Street, Singarapettai, Krishnagiri</p>
                </div>
                <div class="col-md-4 fo-grid1">
                        <p><i class="fa fa-phone" aria-hidden="true"></i>+91 9786885165</p>	
                </div>
                <div class="col-md-4 fo-grid1">
                    <p><a href="mailto:anbarazu93@gmail.com"><i class="fa fa-envelope-o" aria-hidden="true"></i>anbarazu93@gmail.com</a></p>
                </div>
                <div class="clearfix"></div>
                
                </div>
        </div>
    <div class="copy-right">
        <p> &copy; 2017 KTI store. All Rights Reserved | Design by  <a href="https://veluiknow.000webhostapp.com"> BSm Technologies</a></p>
    </div>
</div>

app/views/layouts/_header.html.erb
<a href="offer.html"><%= image_tag "download.png", class: "img-head" %></a>
<div class="header">

		<div class="container">
			
			<div class="logo">
				<h1 ><a href="<%= pages_dashboard_path%>"><b>K<br>T<br>I</b> &nbsp <%=image_tag "logo.png", class: "logo-image"%></a></h1>
			</div>
			<div class="head-t">
				<ul class="card">
					<li><a href="#" ><i class="fa fa-heart" aria-hidden="true"></i>Wishlist</a></li>
					<%if current_user.present?%>
					<li><a href="<%=orders_path(id: current_user.id)%>" ><i class="fa fa-file-text-o" aria-hidden="true"></i>Order History</a></li>
					
					<li><a href="#" ><i class="fa fa-ship" aria-hidden="true"></i>Shipping</a></li>
					<%end%>
					<%unless current_user.present?%>
					<li><a href="<%= pages_register_path%>" ><i class="fa fa-arrow-right" aria-hidden="true"></i>Register</a></li>
					<li><a href="<%= pages_login_path%>" ><i class="fa fa-user" aria-hidden="true"></i>Login</a></li>
					<%else%>

					<li><a href="<%= pages_logout_path%>" ><i class="fa fa-user" aria-hidden="true"></i>Logout</a></li>
					<% end %>

				</ul>	
			</div>
			<%=link_to "Admin", pages_dashboard_path %> 
			<div class="header-ri">
				<ul class="social-top">
					<li><a href="#" class="icon facebook"><i class="fa fa-facebook" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon twitter"><i class="fa fa-twitter" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon pinterest"><i class="fa fa-pinterest-p" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i><span></span></a></li>
				</ul>	
			</div>
		

				<div class="nav-top">
					<nav class="navbar navbar-default">
					
					<div class="navbar-header nav_2">
						<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						

					</div> 
					<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
						<ul class="nav navbar-nav ">
							<li class=" active"><a href="<%= pages_dashboard_path%>" class="hyper "><span>Home</span></a></li>	
							
							<li class="dropdown ">
								<a href="#" class="dropdown-toggle  hyper" data-toggle="dropdown" ><span>Milk<b class="caret"></b></span></a>
								<ul class="dropdown-menu multi">
									<div class="row">
										<div class="col-sm-3">
											<ul class="multi-column-dropdown">
			
												<li><a href="<%= pages_dashboard_path(id: 1)%>"><i class="fa fa-angle-right" aria-hidden="true"></i>A1 Milk</a></li>
										
											</ul>
										
										</div>
										<div class="col-sm-3">
										
											<ul class="multi-column-dropdown">
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Breakfast &amp; Cereal</a></li>
										
											</ul>
										
										</div>
										<div class="col-sm-3">
										
											<ul class="multi-column-dropdown">
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Pickle & Condiment</a></li>
										
											</ul>
										</div>
										<div class="col-sm-3 w3l">
											<a href="#"><%= image_tag "me.png", class: "img-responsive"%></a>
										</div>
										<div class="clearfix"></div>
									</div>	
								</ul>
							</li>
							<li class="dropdown">
							
								<a href="#" class="dropdown-toggle hyper" data-toggle="dropdown" ><span> Vegetables <b class="caret"></b></span></a>
								<ul class="dropdown-menu multi multi1">
									<div class="row">
										<div class="col-sm-3">
											<ul class="multi-column-dropdown">
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Ayurvedic </a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Baby Care</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Cosmetics</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Deo & Purfumes</a></li>
										
											</ul>
											
										</div>
										<div class="col-sm-3">
											
											<ul class="multi-column-dropdown">
												<li><a href="#"> <i class="fa fa-angle-right" aria-hidden="true"></i>Hair Care </a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Oral Care</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Personal Hygiene</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Skin care</a></li>
										
											</ul>
											
										</div>
										<div class="col-sm-3">
											
											<ul class="multi-column-dropdown">
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Fashion Accessories </a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Grooming Tools</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Shaving Need</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Sanitary Needs</a></li>
										
											</ul>
										</div>
										<div class="col-sm-3 w3l">
											<a href="#"><%= image_tag "me1.png" ,class: "img-responsive"%></a>
										</div>
										<div class="clearfix"></div>
									</div>	
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle hyper" data-toggle="dropdown" ><span>Other Products<b class="caret"></b></span></a>
								<ul class="dropdown-menu multi multi2">
									<div class="row">
										<div class="col-sm-3">
											<ul class="multi-column-dropdown">
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Cleaning Accessories</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>CookWear</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Detergents</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Gardening Needs</a></li>
										
											</ul>
										
										</div>
										<div class="col-sm-3">
											
											<ul class="multi-column-dropdown">
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Kitchen & Dining</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>KitchenWear</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Pet Care</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Plastic Wear</a></li>
										
											</ul>
										
										</div>
										<div class="col-sm-3">
										
											<ul class="multi-column-dropdown">
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Pooja Needs</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Serveware</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Safety Accessories</a></li>
												<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Festive Decoratives </a></li>
										
											</ul>
										</div>
										<div class="col-sm-3 w3l">
											<a href="#"><%= image_tag "me2.png", class: "img-responsive" %></a>
										</div>
										<div class="clearfix"></div>
									</div>	
								</ul>
							</li>
							
							<li><a href="#" class="hyper"> <span>Customer Care</span></a></li>
							<li><a href="<%= pages_contact_path%>" class="hyper"><span>Contact Us</span></a></li>
						</ul>
					</div>
					</nav>
					 <div class="cart" >
					
						<span class="fa fa-shopping-cart my-cart-icon"><span class="badge badge-notify my-cart-badge"></span></span>
					</div>
					<div class="clearfix"></div>
				</div>
					
				</div>			
</div>
  <!---->
  <style>
  .logo-image{
	  height: 50px;
	  width: 300px;
  }
  </style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kurinjithinai</title>
    <%= csrf_meta_tags %>
    <%=favicon_link_tag 'logo.png', rel: 'apple-touch-icon', type: 'image/png'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
  function hideURLbar(){ window.scrollTo(0,1); } </script>
  <!-- //for-mobile-apps -->
  <link href="../assets/css/bootstrap.css" rel='stylesheet' type='text/css' />
  <!-- Custom Theme files -->
  <link href="../assets/css/style.css" rel='stylesheet' type='text/css' />
  <!-- js -->
     <script src="../assets/js/jquery-1.11.1.min.js"></script>
  <!-- //js -->
  <!-- start-smoth-scrolling -->
  <script type="text/javascript" src="../assets/js/move-top.js"></script>
  <script type="text/javascript" src="../assets/js/easing.js"></script>
  <script type="text/javascript">
    jQuery(document).ready(function($) {
      $(".scroll").click(function(event){		
        event.preventDefault();
        $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
      });
    });
  </script>
  <!-- start-smoth-scrolling -->

  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
  <!--- start-rate---->
  <script src="../assets/js/jstarbox.js"></script>
    <link rel="stylesheet" href="../assets/css/jstarbox.css" type="text/css" media="screen" charset="utf-8" />
      <script type="text/javascript">
        jQuery(function() {
        jQuery('.starbox').each(function() {
          var starbox = jQuery(this);
            starbox.starbox({
            average: starbox.attr('data-start-value'),
            changeable: starbox.hasClass('unchangeable') ? false : starbox.hasClass('clickonce') ? 'once' : true,
            ghosting: starbox.hasClass('ghosting'),
            autoUpdateAverage: starbox.hasClass('autoupdate'),
            buttons: starbox.hasClass('smooth') ? false : starbox.attr('data-button-count') || 5,
            stars: starbox.attr('data-star-count') || 5
            }).bind('starbox-value-changed', function(event, value) {
            if(starbox.hasClass('random')) {
            var val = Math.random();
            starbox.next().text(' '+val);
            return val;
            } 
          })
        });
      });
      </script>
  <body>
  <%= render partial: "layouts/header"%>
    <%= yield %>
  </body>
  <div class="footer">
  <%= render partial: "layouts/footer"%>
  </div>
</html>